### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-reservation#9]
* Branch `release`
* Pre-Release 1 auf diesen commiten und mit `pre-release-1` taggen
* Auf Heroku deployen
* Heroku `dev` Serive einrichten

Siehe [Release Management](https://github.com/ob-vss-ss18/ppl-core/wiki/Release-Management)

**Comment by Johdeath** [comment]
https://github.com/ob-vss-ss18/ppl-reservation/releases/tag/pre-release-1

**Comment by hilakista** [comment]
Bitte Issue schließen wenn fertig
